[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/start"
  to = "/start.html"
  status = 200

[[redirects]]
  from = "/track"
  to = "/track.html"
  status = 200

[[redirects]]
  from = "/skincare-manufacturer-jamaica"
  to = "/skincare-manufacturer-jamaica.html"
  status = 200

[[redirects]]
  from = "/cost-skincare-business-jamaica"
  to = "/cost-skincare-business-jamaica.html"
  status = 200

[[redirects]]
  from = "/__/auth/*"
  to = "https://najah-chemist.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true
