// recommendation-agent/sync.js — PURE builders for the canonical `recommendations`
// record (persist-at-generation). No Firestore/network: fully unit-testable.
//
// The scorer (lead-agent) owns SCORING. This module owns turning a scored lead into
// a persistent recommendation record with a permanent ID and a canonical state — it
// does NOT change any score, probability, ranking, or offer.

const RM = require('../_shared/recommendation-model');
const { customerIdFor } = require('../_shared/identity');

// Derived action label + time estimate (presentation read-model). Mirrors the
// dashboard's actionForLead/ACTION_MIN so the UI never recomputes it (Phase E).
const ACTION_MIN = { whatsapp: 5, moqQuote: 10, email: 7 };
function actionForLead(intel, name) {
  if (intel.recommendedOffer === 'Manufacturing' && intel.opportunitySource === 'newlead') {
    return { action: `Send MOQ quote to ${name}`, minutes: ACTION_MIN.moqQuote };
  }
  if (intel.preferredChannel === 'whatsapp') return { action: `WhatsApp ${name}`, minutes: ACTION_MIN.whatsapp };
  return { action: `Email ${name}`, minutes: ACTION_MIN.email };
}
function whyFor(intel) {
  if (Array.isArray(intel.whyRecommended) && intel.whyRecommended.length) return intel.whyRecommended;
  const w = [];
  if (intel.recommendedOffer === 'Manufacturing') w.push('Manufacturing lead');
  if (intel.opportunitySource === 'hot') w.push('Hot / engaged');
  if (Array.isArray(intel.intentSignals) && intel.intentSignals.length) w.push(String(intel.intentSignals[0]));
  return w.length ? w : ['Scored opportunity'];
}

// Honest = real + primary + not-suspicious (mirrors leadFilters.honest in the dashboard,
// the single downstream-exclusion rule). Missing flags default to real/primary.
function isHonest(intel) {
  return !!intel
    && intel.isTest !== true
    && intel.isPrimaryRecord !== false
    && intel.suspiciousLead !== true;
}

// A recommendation should be GENERATED for an honest lead that is not already a closed
// lifecycle (Won/Lost from the scorer's view). Order-based resolution is the reconciler's
// job; this just avoids minting recs for leads the scorer already considers done.
function isGeneratable(intel) {
  if (!isHonest(intel)) return false;
  if (intel.lifecycleStage === 'Won' || intel.lifecycleStage === 'Lost') return false;
  return true;
}

// Derived fields refreshed on every sync. NEVER includes id/state/generatedAt/history.
function derivedFromIntel(intel, lead) {
  const i = intel || {}, l = lead || {};
  const t = RM.recType(i);
  const pv = (i.potentialValue && Number(i.potentialValue.value)) || 0;
  const email = (l.email || '').trim();
  const phone = l.whatsapp || '';
  const name = String(l.name || '').trim() || ('Lead ' + String(i.leadId || '').slice(0, 6));
  const ev = Math.round(Number(i.expectedValue) || 0);
  const act = actionForLead(i, name);
  const replied = Array.isArray(i.intentSignals) && i.intentSignals.some(s => /repl/i.test(String(s)));
  return {
    leadId: i.leadId,
    customerId: customerIdFor({ email, phone }),
    recommendationType: t.key,
    recommendationLabel: t.label,
    typeCode: t.tc,
    recommendedChannel: t.channel,
    name: String(l.name || '').trim() || null,
    recommendedOffer: i.recommendedOffer || null,
    suggestedProduct: i.suggestedProduct || null,
    leadSource: l.source || l.leadSource || l.channel || i.opportunitySource || null,
    opportunitySource: i.opportunitySource || null,
    urgencyScore: Number(i.urgencyScore) || 0,
    score: Number(i.score) || 0,
    scoreLabel: i.scoreLabel || null,
    closeProbability: Number(i.closeProbability) || 0,
    potentialValue: pv,
    expectedValue: ev,
    // Read-model fields so the dashboard renders a row from the record alone (Phase E):
    action: act.action,
    minutes: act.minutes,
    roi: act.minutes > 0 ? ev / act.minutes : ev,
    why: whyFor(i),
    replied,
    lastMeaningfulActivity: i.lastMeaningfulActivity || null,
    scorerVersion: i.recommendationVersion || null,
  };
}

// A brand-new recommendation record (first generation). Stamps the permanent ID,
// the frozen generatedAt, and the qualifying-order baseline (lead's last activity at
// generation time, falling back to now).
function newRecord(intel, lead, nowISO) {
  const d = derivedFromIntel(intel, lead);
  const t = RM.recType(intel);
  const recommendationId = RM.newRecommendationId(d.leadId, t.tc, nowISO);
  const baseline = (intel && intel.lastMeaningfulActivity) || nowISO;
  return {
    recommendationId,
    state: RM.STATE.GENERATED,
    generatedAt: nowISO,
    baselineActivityAt: baseline,
    lastSyncedAt: nowISO,
    lastStateChangeAt: nowISO,
    stateReason: 'Generated by scorer',
    // resolution placeholders (filled by the reconciler / founder action):
    orderId: null, outcomeId: null,
    expectedRevenue: d.expectedValue, actualRevenue: null, revenueVariance: null,
    resolvedAt: null, resolvedBy: null, matchMethod: null, matchConfidence: null,
    agentOwner: 'recommendation-agent',
    history: [{ at: nowISO, from: null, to: RM.STATE.GENERATED, reason: 'Generated by scorer', actor: 'recommendation-agent', eventType: 'generated', source: 'scorer', data: null }],
    ...d,
  };
}

// Refresh derived fields on an existing open record WITHOUT touching identity, state,
// generatedAt, baseline, resolution, or history. Returns the fields to merge.
function refreshedDerived(existing, intel, lead, nowISO) {
  const d = derivedFromIntel(intel, lead);
  // expectedRevenue mirrors the live expectedValue ONLY while still active (so the
  // forecast stays current); once resolved we freeze whatever was recorded.
  const patch = { ...d, lastSyncedAt: nowISO };
  if (!RM.isTerminalState(existing.state)) patch.expectedRevenue = d.expectedValue;
  // Never let a derived refresh overwrite these:
  delete patch.recommendationId;
  return patch;
}

module.exports = { isHonest, isGeneratable, derivedFromIntel, newRecord, refreshedDerived };
